---
- name: Build, Push Docker image, and Deploy to Kubernetes
  hosts: all
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3.10
    docker_image_name: "jacekcracow/abctechnologies-latest-with-ansible"
    docker_image_tag: "{{ build_number }}"

  tasks:
    - name: Docker Build
      command: docker build -t "{{ docker_image_name }}:{{ docker_image_tag }}" .
      args:
        chdir: .
      delegate_to: localhost
      run_once: true

    - name: Docker Login
      community.docker.docker_login:
        username: "{{ docker_username }}"
        password: "{{ docker_password }}"
        registry: "https://index.docker.io/v1/"
      delegate_to: localhost
      run_once: true

    - name: Docker Push
      command: docker push "{{ docker_image_name }}:{{ docker_image_tag }}"
      delegate_to: localhost
      run_once: true

    - name: Docker Logout
      community.docker.docker_login:
        registry: "https://index.docker.io/v1/"
        state: absent
      delegate_to: localhost
      run_once: true

    - name: Ensure namespace abc-technologies exists
      kubernetes.core.k8s:
        kubeconfig: "{{ ansible_user_dir }}/.kube/config"
        state: present
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: abc-technologies

    - name: Ensure .kube directory exists
      file:
        path: "{{ ansible_user_dir }}/.kube"
        state: directory
        mode: 0755

    - name: Copy kubeconfig to the node
      copy:
        src: /home/jacek/.kube/config
        dest: "{{ ansible_user_dir }}/.kube/config"
        mode: 0600
      delegate_to: localhost
      run_once: true
      become: true

    - name: Deploy Kubernetes Deployment
      kubernetes.core.k8s:
        kubeconfig: "{{ ansible_user_dir }}/.kube/config"
        state: present
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: abc-technologies-deployment
            namespace: abc-technologies
            labels:
              app: abc-technologies
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: abc-technologies
            template:
              metadata:
                labels:
                  app: abc-technologies
              spec:
                containers:
                  - name: abc-technologies-container
                    image: "{{ docker_image_name }}:{{ docker_image_tag }}"
                    ports:
                      - containerPort: 8080
                    resources:
                      limits:
                        cpu: "1"
                        memory: "512Mi"
                      requests:
                        cpu: "500m"
                        memory: "256Mi"

    - name: Deploy Kubernetes Service
      kubernetes.core.k8s:
        kubeconfig: "{{ ansible_user_dir }}/.kube/config"
        state: present
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: abc-technologies-service
            namespace: abc-technologies
          spec:
            selector:
              app: abc-technologies
            ports:
              - protocol: TCP
                port: 8080
                targetPort: 8080
            type: NodePort
...
