---
- hosts: localhost
  connection: local
  tasks:
    - name: Docker Build
      command: docker build -t jacekcracow/abctechnologies-latest-with-ansible:{{ build_number }} .
      args:
        chdir: .

    - name: Docker Login
      community.docker.docker_login:
        username: "{{ docker_username }}"
        password: "{{ docker_password }}"
        registry: "https://index.docker.io/v1/"

    - name: Docker Push
      command: docker push jacekcracow/abctechnologies-latest-with-ansible:{{ build_number }}

    - name: Docker Pull (Optional)
      community.docker.docker_image:
        name: "jacekcracow/abctechnologies-latest-with-ansible:{{ build_number }}"
        source: pull

    - name: Remove Previous Container
      community.docker.docker_container:
        name: abctechnologies-container
        state: absent

    - name: Docker Run
      community.docker.docker_container:
        name: abctechnologies-container
        image: "jacekcracow/abctechnologies-latest-with-ansible:{{ build_number }}"
        ports:
          - "8090:8080"
        detach: yes
        state: started

    - name: Docker Logout
      community.docker.docker_login:
        registry: "https://index.docker.io/v1/"
        state: absent
