---
- hosts: knode1  # Define the target host (knode1)
  become: true # Required for docker commands

  vars:
    docker_image: jacekcracow/abctechnologies-latest:{{ build_number }} # Use a variable for the image tag
    docker_port: 8090

  tasks:
    - name: Docker Login
      docker_login:
        username: "{{ docker_username }}" # Provided via extra vars from Jenkins
        password: "{{ docker_password }}" # Provided via extra vars from Jenkins
        registry: "https://index.docker.io/v1/" # Explicitly define the registry

    - name: Docker Run
      docker_container:
        name: abctechnologies-container # Give the container a name
        image: "{{ docker_image }}"
        ports:
          - "{{ docker_port }}:8080" # Map host port to container port
        detach: yes # Run in detached mode
        remove: yes # Remove container on stop
        state: started # Ensure container is started


    - name: Docker Logout
      docker_logout:
        registry: "https://index.docker.io/v1/" # Explicitly define the registry
