---
- hosts: all # Or specify your host group/name from the inventory
  become: true # Required for Docker commands

  tasks:
    - name: Docker Login
      docker_login:
        username: "{{ docker_username }}"
        password: "{{ docker_password }}"
        registry: "https://index.docker.io/v1/" # Explicitly define the registry

    - name: Docker Pull (Optional)
      docker_image:
        name: "jacekcracow/abctechnologies-latest-with-ansible:{{ build_number }}"
        source: pull

    - name: Docker Run
      docker_container:
        name: abctechnologies-container
        image: "jacekcracow/abctechnologies-latest-with-ansible:{{ build_number }}"
        ports:
          - "8090:8080"  # Correct port mapping
        detach: yes
        remove: yes
        state: started

    - name: Docker Logout
      docker_logout:
        registry: "https://index.docker.io/v1/" # Explicitly define the registry
