---
- name: Build and Deploy Docker Image
  hosts: knode1
  become: false
  vars:
    docker_image_name: "jacekcracow/abctechnologies-latest-with-ansible"
    build_number: "{{ lookup('env', 'BUILD_NUMBER') }}"
    dockerhub_user: "{{ lookup('env', 'DOCKERHUB_CREDENTIALS_USR') }}"
    dockerhub_password: "{{ lookup('env', 'DOCKERHUB_CREDENTIALS_PSW') }}"
    container_port: 8080
    host_port: 8090

  tasks:
    - name: Build Docker image
      docker_image:
        name: "{{ docker_image_name }}:{{ build_number }}"
        path: .
        state: present

    - name: Log in to Docker Hub
      docker_login:
        username: "{{ dockerhub_user }}"
        password: "{{ dockerhub_password }}"

    - name: Push Docker image to Docker Hub
      docker_image:
        name: "{{ docker_image_name }}:{{ build_number }}"
        push: yes

    - name: Run the Docker container
      docker_container:
        name: abctechnologies-container
        image: "{{ docker_image_name }}:{{ build_number }}"
        state: started
        restart_policy: unless-stopped
        ports:
          - "{{ host_port }}:{{ container_port }}"

    - name: Logout from Docker
      command: docker logout
