---
- name: Build and Deploy Docker Image
  hosts: knode1
  become: true
  vars:
    docker_image_name: "jacekcracow/abctechnologies-latest-with-ansible"
    build_number: "{{ lookup('env', 'BUILD_NUMBER') }}"
    dockerhub_user: "{{ lookup('env', 'DOCKERHUB_CREDENTIALS_USR') }}"
    dockerhub_password: "{{ lookup('env', 'DOCKERHUB_CREDENTIALS_PSW') }}"
    
  tasks:
    - name: Build Docker image
      community.docker.docker_image:
        name: "{{ docker_image_name }}:{{ build_number }}"
        build:
          path: .
          dockerfile: Dockerfile
        source: build
        state: present

    - name: Log in to Docker Hub
      community.docker.docker_login:
        username: "{{ dockerhub_user }}"
        password: "{{ dockerhub_password }}"

    - name: Push Docker image to Docker Hub
      community.docker.docker_image:
        shell: "{{ docker_image_name }}:{{ build_number }}"
        
    - name: Run the Docker container
      docker_container:
        name: abctechnologies-container
        image: "{{ docker_image_name }}:{{ build_number }}"
        state: started
        restart_policy: unless-stopped
        ports:
          - "{{ host_port }}:{{ container_port }}"

    - name: Logout from Docker
      command: docker logout
