---
- hosts: knode1
  become: true
  tasks:
    - name: Docker Login
      docker_login:
        username: "{{ docker_username }}"
        password: "{{ docker_password }}"
        registry: "https://index.docker.io/v1/"

    - name: Tag Docker Image
      command: docker tag jacekcracow/abctechnologies-latest-with-ansible:{{ build_number }} jacekcracow/abctechnologies-latest-with-ansible:{{ build_number }}

    - name: Docker Push
      command: docker push jacekcracow/abctechnologies-latest-with-ansible:{{ build_number }}

    - name: Docker Pull (Optional)
      docker_image:
        name: "jacekcracow/abctechnologies-latest-with-ansible:{{ build_number }}"
        source: pull
  
    - name: Docker Run
      docker_container:
        name: abctechnologies-container
        image: "jacekcracow/abctechnologies-latest-with-ansible:{{ build_number }}"
        ports:
          - "8090:8080"
        detach: yes
        remove: yes
        state: started

    - name: Docker Logout
      docker_logout:
        registry: "https://index.docker.io/v1/"
