---
- name: Build and Publish Docker Image
  hosts: knode1
  gather_facts: false

  tasks:
    - name: Build Docker Image
      command: "docker build -t jacekcracow/abctechnologies-latest-with-ansible

    - name: Log in to Docker Hub
      shell: "docker login -u {{ docker_username }} -p {{ docker_password }}"
      register: docker_login_result
      ignore_errors: yes

    - name: Push to Docker Hub
      shell: "docker push jacekcracow/abctechnologies-latest-with-ansible"
      environment:
        DOCKER_CLI_AGGREGATE: "1"
      when: docker_login_result is success
